[build] # Make sure you don't have a duplicate [build] context!
  functions = "functions"  
  
[[plugins]]
  package = "@netlify/plugin-local-install-core"

[[redirects]]
  from = "/*"
  to = "/404/index.html"
  status = 404